import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });
import { SwapTokenContextProvider } from "../Context/SwapContext";

import { NavBar } from "../Components/index";
export const metadata = {
  title: "Fun Fire Swap",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <SwapTokenContextProvider>
        <body className={inter.className}>
          <NavBar />
          {children}
        </body>
      </SwapTokenContextProvider>
    </html>
  );
}
